Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
RunWait = "600000s"
Suite = "Ed25519"
PreScript = "testPreScript.toml"
RoundDuration = 5000000000
timeout = 1000
PercentageTxPay = 5
DistributionMeanFileSize = 100
DistributionVarianceFileSize = 5
DistributionMeanContractDuration = 10
DistributionVarianceContractDuration = 50
DistributionMeanInitialPower = 9000000000000000000
DistributionVarianceInitialPower = 9000000000000000
Nodes = 15
BlockSize = 1000000
SectorNumber = 1
NumberOfPayTXsUpperBound = 10

Hosts
15