Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
RunWait = "600000s"
Suite = "bn256.adapter"
PreScript = "ChainBoostPreScript.toml"
ProtocolTimeout = 1000
timeout = 250
DistributionMeanFileSize = 100
DistributionVarianceFileSize = 5
DistributionMeanServAgrDuration = 10
DistributionVarianceServAgrDuration = 50
DistributionMeanInitialPower = 9000000000000000000
DistributionVarianceInitialPower = 9000000000000000
BlockSize = 25000
SectorNumber = 1
NumberOfPayTXsUpperBound = 200
PercentageTxPay = 30
SimulationSeed = 10
SCRoundDuration = 2
MCRoundDuration = 4
EpochCount = 2
NbrSubTrees = 1
Nodes = 32
CommitteeWindow = 5
Threshold = 4   
SimState = 2

Hosts
32