Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
RunWait = "600000s"
Suite = "bn256.adapter"
PreScript = "ChainBoostPreScript.toml"
SimulationRounds = 18
timeout = 180
FileSizeDistributionMean = 100
FileSizeDistributionVariance = 5
ServAgrDurationDistributionMean = 10
ServAgrDurationDistributionVariance = 50
InitialPowerDistributionMean = 9000000000000000000
InitialPowerDistributionVariance = 9000000000000000
BlockSize = 25000
SectorNumber = 1
NumberOfPayTXsUpperBound = 200
PercentageTxPay = 30
SimulationSeed = 10
SCRoundDuration = 1
MCRoundDuration = 2
EpochCount = 2
NbrSubTrees = 1
Nodes = 10
CommitteeWindow = 5
Threshold = 4   
SimState = 2

Hosts
10