Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
RunWait = "600000s"
Suite = "bn256.adapter"
PreScript = "testPreScript.toml"
RoundDuration = 10
ProtocolTimeout = 100
timeout = 250
PercentageTxPay = 30
DistributionMeanFileSize = 100
DistributionVarianceFileSize = 5
DistributionMeanContractDuration = 10
DistributionVarianceContractDuration = 50
DistributionMeanInitialPower = 900000000000000000
DistributionVarianceInitialPower = 9000000000000000
Nodes = 20
BlockSize = 200000
SectorNumber = 1
NumberOfPayTXsUpperBound = 200
SimulationSeed = 10
NbrSubTrees = 2
Threshold = 15
EpochDuration = 2
CommitteeWindow = 10

Hosts
20