Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
RunWait = "600000s"
Suite = "Ed25519"
PreScript = "testPreScript.toml"
RoundDuration = 2
ProtocolTimeout = 10
timeout = 250
PercentageTxPay = 30
DistributionMeanFileSize = 100
DistributionVarianceFileSize = 5
DistributionMeanContractDuration = 10
DistributionVarianceContractDuration = 50
DistributionMeanInitialPower = 900000000000000000
DistributionVarianceInitialPower = 9000000000000000
Nodes = 10
BlockSize = 200000
SectorNumber = 1
NumberOfPayTXsUpperBound = 200
SimulationSeed = 10

Hosts
10