Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
Suite = "Ed25519"
PreScript = "testPreScript.toml"
RoundDuration = 13000000000
timeout = 1000
PercentageTxPoR = 40
PercentageTxPay = 25
PercentageTxEscrow = 35
DistributionMeanFileSize = 100
DistributionVarianceFileSize = 5
DistributionMeanContractDuration = 10
DistributionVarianceContractDuration = 50
DistributionMeanInitialPower = 9000000000000000000
DistributionVarianceInitialPower = 9000000000000000
Nodes = 300
BlockSize = 13

Hosts
300