Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
RunWait = "600000s"
Suite = "Ed25519"
PreScript = "testPreScript.toml"
RoundDuration = 15000000000
timeout = 1000
PercentageTxPoR = 40
PercentageTxPay = 25
PercentageTxEscrow = 35
DistributionMeanFileSize = 100
DistributionVarianceFileSize = 5
DistributionMeanContractDuration = 10
DistributionVarianceContractDuration = 50
DistributionMeanInitialPower = 9000000000000000000
DistributionVarianceInitialPower = 9000000000000000
Nodes = 50
BlockSize = 300

Hosts
50