Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
RunWait = "600000s"
Suite = "Ed25519"
PreScript = "testPreScript.toml"
RoundDuration = 15
ProtocolTimeout = 250
timeout = 5000
PercentageTxPay = 30
DistributionMeanFileSize = 100
DistributionVarianceFileSize = 5
DistributionMeanContractDuration = 10
DistributionVarianceContractDuration = 50
DistributionMeanInitialPower = 900000000000000000
DistributionVarianceInitialPower = 9000000000000000
Nodes = 100
BlockSize = 200000
SectorNumber = 1
NumberOfPayTXsUpperBound = 200

Hosts
100