Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
RunWait = "600000s"
Suite = "bn256.adapter"
PreScript = "testPreScript.toml"
ProtocolTimeout = 1000
timeout = 250
PercentageTxPay = 30
DistributionMeanFileSize = 100
DistributionVarianceFileSize = 5
DistributionMeanContractDuration = 10
DistributionVarianceContractDuration = 50
DistributionMeanInitialPower = 9000000000000000000
DistributionVarianceInitialPower = 900000000000000000
BlockSize = 2000
SectorNumber = 1
NumberOfPayTXsUpperBound = 200
SimulationSeed = 10
SCRoundDuration = 2
MCRoundDuration = 4
EpochCount = 2
NbrSubTrees = 1
Nodes = 50
CommitteeWindow = 10
Threshold = 9

Hosts
50