Servers = 1
Simulation = "BaseDFS"
BF = 2
Rounds = 0
timeout = 180
RunWait = "600000s"
Suite = "bn256.adapter"
NbrSubTrees = 1
PreScript = "ChainBoostPreScript.toml"
FileSizeDistributionMean = 100
FileSizeDistributionVariance = 5
ServAgrDurationDistributionMean = 10
ServAgrDurationDistributionVariance = 50
InitialPowerDistributionMean = 9000000000000000000
InitialPowerDistributionVariance = 9000000000000000
MainChainBlockSize = 25000
SideChainBlockSize = 4000
SectorNumber = 1
NumberOfPayTXsUpperBound = 200
PercentageTxPay = 30
SimulationSeed = 5
SimulationRounds = 5
SCRoundDuration = 30
MCRoundDuration = 60
MCRoundPerEpoch = 2
Nodes = 10
CommitteeWindow = 5
Threshold = 4   
SimState = 2

Hosts
10