Servers = 1
Simulation = "ChainBoost"
BF = 2
Rounds = 100
timeout = 120
RunWait = "600000s"
Suite = "bn256.adapter"
FileSizeDistributionMean = 115
FileSizeDistributionVariance = 5
ServAgrDurationDistributionMean = 25
ServAgrDurationDistributionVariance = 10
PercentageTxPay = 30
MCRoundDuration = 5      
MainChainBlockSize = 10000
SideChainBlockSize = 10000
SectorNumber = 2
NumberOfPayTXsUpperBound = 10
SimulationRounds = 5
SimulationSeed = 100
NbrSubTrees = 1
Threshold = 4 
SCRoundDuration = 1
CommitteeWindow = 5
MCRoundPerEpoch = 2
SimState = 2
Nodes = 40

Hosts
40