Servers = 8
Simulation = "ChainBoost"
BF = 2
Rounds = 100
timeout = 12000000
RunWait = "600000s"
Suite = "bn256.adapter"
FileSizeDistributionMean = 115
FileSizeDistributionVariance = 5
ServAgrDurationDistributionMean = 25
ServAgrDurationDistributionVariance = 10
PercentageTxPay = 30  
MainChainBlockSize = 1
SideChainBlockSize = 1
SectorNumber = 2
NumberOfPayTXsUpperBound = 100
NumberOfActiveContractsPerServer = 2
SimulationRounds = 50
SimulationSeed = 100
NbrSubTrees = 1
CommitteeWindow = 5
Threshold = 4 
StoragePaymentEpoch = 2
MCRoundPerEpoch = 2
MCRoundDuration = 10 
SCRoundDuration = 1
SimState = 2
Nodes = 100

Hosts
100