Servers = 1
Simulation = "ChainBoost"
BF = 2
Rounds = 0
timeout = 900000
RunWait = "600000s"
Suite = "bn256.adapter"
NbrSubTrees = 1
PreScript = "ChainBoostPreScript.toml"
FileSizeDistributionMean = 100
FileSizeDistributionVariance = 5
ServAgrDurationDistributionMean = 20
ServAgrDurationDistributionVariance = 50
InitialPowerDistributionMean = 9000000000000000000
InitialPowerDistributionVariance = 9000000000000000
SectorNumber = 2
NumberOfPayTXsUpperBound = 30
PercentageTxPay = 30
SCRoundDuration = 2
MCRoundDuration = 10
MCRoundPerEpoch = 2
Nodes = 10
CommitteeWindow = 5
Threshold = 4   
SimState = 2
SimulationSeed = 5
SimulationRounds = 50
MainChainBlockSize = 27000
SideChainBlockSize = 20000

Hosts
10