Servers = 8
Simulation = "ChainBoost"
BF = 2
Rounds = 100
timeout = 12000000
RunWait = "12000000s"
Suite = "bn256.adapter"
FileSizeDistributionMean = 115
FileSizeDistributionVariance = 5
ServAgrDurationDistributionMean = 40
ServAgrDurationDistributionVariance = 20
PercentageTxPay = 30
PayPercentOfTransactions = 0.02
NumberOfPayTXsUpperBound = 100
SectorNumber = 2
NumberOfActiveContractsPerServer = 64
SimulationRounds = 61
SimulationSeed = 100
NbrSubTrees = 1
CommitteeWindow = 500
Threshold = 334
StoragePaymentEpoch = 0
MCRoundPerEpoch = 10
SCRoundPerEpoch = 30
MCRoundDuration = 30
SCRoundDuration = 10
VMs = ["192.168.3.220", "192.168.3.221", "192.168.3.222", "192.168.3.223", "192.168.3.224", "192.168.3.225", "192.168.3.226", "192.168.3.227", "192.168.3.228", "192.168.3.229"]
Nodes = 8000

Hosts, SimState, MainChainBlockSize, SideChainBlockSize 
8000, 1, 1000000, 1000000