Servers = 1
Simulation = "ChainBoost"
BF = 8
Rounds = 0
timeout = 120
RunWait = "600000s"
Suite = "bn256.adapter"
FileSizeDistributionMean = 115
FileSizeDistributionVariance = 5
ServAgrDurationDistributionMean = 25
ServAgrDurationDistributionVariance = 10
InitialPowerDistributionMean = 9000000000000000000
InitialPowerDistributionVariance = 9000000000000000
Nodes = 4000
SimulationSeed=9

Hosts
4000