Servers = 1
Simulation = "ChainBoost"
BF = 2
Rounds = 0
timeout = 900000
RunWait = "600000s"
Suite = "bn256.adapter"
NbrSubTrees = 1
FileSizeDistributionMean = 115
FileSizeDistributionVariance = 5
ServAgrDurationDistributionMean = 25
ServAgrDurationDistributionVariance = 10
InitialPowerDistributionMean = 9000000000000000000
InitialPowerDistributionVariance = 9000000000000000
SectorNumber = 2
SCRoundDuration = 60
MCRoundDuration = 180
MCRoundPerEpoch = 2
CommitteeWindow = 5
Threshold = 4   
MainChainBlockSize = 30000
SideChainBlockSize = 25000
Nodes = 50
NumberOfPayTXsUpperBound = 50
PercentageTxPay = 30
SimState = 1
SimulationSeed = 5
SimulationRounds = 22

Hosts
50