Login = "ubuntu"
Host = "ec2-3-83-2-13.compute-1.amazonaws.com:22"
Project = "SAFER"
Experiment = "Dissent-CS"
ProxyAddress = "localhost"
MonitorAddress = "ec2-3-83-2-13.compute-1.amazonaws.com"
MonitorPort = 10000
Servers = 1
Simulation = "ChainBoost"
Hosts = 0
Debug = 0
RunWait = "600000s"
Suite = "bn256.adapter"
PreScript = "ChainBoostPreScript.toml"
Tags = ""
MCRoundDuration = 180
PercentageTxPay = 30
MainChainBlockSize = 30000
SideChainBlockSize = 25000
SectorNumber = 2
NumberOfPayTXsUpperBound = 50
SimulationRounds = 22
SimulationSeed = 5
NbrSubTrees = 1
Threshold = 4
SCRoundDuration = 60
CommitteeWindow = 5
MCRoundPerEpoch = 2
SimState = 1
