Login = "zam20015"
Host = "csi-lab-ssh.engr.uconn.edu:22"
Project = "SAFER"
Experiment = "Dissent-CS"
ProxyAddress = "localhost"
MonitorAddress = "csi-lab-ssh.engr.uconn.edu"
MonitorPort = 10000
Servers = 8
Simulation = "ChainBoost"
Hosts = 0
Debug = 0
RunWait = "600000s"
Suite = "bn256.adapter"
PreScript = ""
Tags = ""
MCRoundDuration = 5
PercentageTxPay = 30
MainChainBlockSize = 2000000
SideChainBlockSize = 2000000
SectorNumber = 2
NumberOfPayTXsUpperBound = 10
SimulationRounds = 50
SimulationSeed = 100
NbrSubTrees = 1
Threshold = 4
SCRoundDuration = 1
CommitteeWindow = 5
MCRoundPerEpoch = 2
SimState = 2
