Login = "zam20015"
Host = "csi-lab-ssh.engr.uconn.edu:22"
Project = "SAFER"
Experiment = "Dissent-CS"
ProxyAddress = "localhost"
MonitorAddress = "csi-lab-ssh.engr.uconn.edu"
MonitorPort = 10000
Servers = 1
Simulation = "ChainBoost"
Hosts = 0
Debug = 0
RunWait = "600000s"
Suite = "bn256.adapter"
PreScript = ""
Tags = ""
MCRoundDuration = 0
PercentageTxPay = 0
MainChainBlockSize = 0
SideChainBlockSize = 0
SectorNumber = 0
NumberOfPayTXsUpperBound = 0
SimulationRounds = 0
SimulationSeed = 9
NbrSubTrees = 0
Threshold = 0
SCRoundDuration = 0
CommitteeWindow = 0
MCRoundPerEpoch = 0
SimState = 0
