Login = "zam20015"
Host = "csi-lab-ssh.engr.uconn.edu:22"
Project = "SAFER"
Experiment = "Dissent-CS"
ProxyAddress = "localhost"
MonitorAddress = "csi-lab-ssh.engr.uconn.edu"
MonitorPort = 10000
Servers = 1
Simulation = "ChainBoost"
Hosts = 0
Debug = 0
RunWait = "600000s"
Suite = "bn256.adapter"
PreScript = ""
Tags = ""
MCRoundDuration = 30
PercentageTxPay = 30
MainChainBlockSize = 20000
SideChainBlockSize = 5000
SectorNumber = 10
NumberOfPayTXsUpperBound = 1000
SimulationRounds = 50
SimulationSeed = 100
NbrSubTrees = 1
Threshold = 4
SCRoundDuration = 5
CommitteeWindow = 5
MCRoundPerEpoch = 5
SimState = 2
